---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'learn-appsync'
Resources:
  GraphQLApiRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: 'appsync.amazonaws.com'
          Action: 'sts:AssumeRole'
      Policies:
      - PolicyName: ServiceRole
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - 'logs:CreateLogGroup'
            - 'logs:CreateLogStream'
            - 'logs:PutLogEvents'
            Resource: '*'
  GraphQLApi:
    Type: 'AWS::AppSync::GraphQLApi'
    Properties:
      Name: !Ref 'AWS::StackName'
      AuthenticationType: API_KEY
      LogConfig:
        CloudWatchLogsRoleArn: !GetAtt 'GraphQLApiRole.Arn'
        FieldLogLevel: ALL
  ApiKey:
    Type: 'AWS::AppSync::ApiKey'
    Properties:
      Expires: 1577750400 # December 31, 2019 12:00:00 AM
      ApiId: !GetAtt 'GraphQLApi.ApiId'
  GraphQLSchema:
    Type: 'AWS::AppSync::GraphQLSchema'
    Properties:
      DefinitionS3Location: './schema.sdl'
      ApiId: !GetAtt 'GraphQLApi.ApiId'
Outputs:
  GraphQLUrl:
    Value: !GetAtt 'GraphQLApi.GraphQLUrl'
  ApiId:
    Value: !GetAtt 'GraphQLApi.ApiId'
  ApiKey:
    Value: !GetAtt 'ApiKey.ApiKey'
